### PR TITLE
add myself to schedule

### PR DESCRIPTION
**Pull request by jesford**
I'll take this Thursday if no one's already planning on it

### CODE REVIEW

**Comment by arokem** [comment]
Do you have any links to the code you want us to look at?

**Comment by jesford** [comment]
Yeah... should I post a link in the README? or email it?

**Comment by arokem** [comment]
A link in the readme would be great.

**Comment by arokem** [comment]
Consider using the guidelines here:
http://fperez.org/py4science/code_reviews.html

**Comment by jesford** [comment]
OK this is my first code review so I'll take a look. Thanks @arokem!

**Comment by arokem** [comment]
Cool. You'd probably also want to send the link to the escience_datasci mailing list, for those not following as closely here :-)

Your branch needs a rebase before it can be merged.

**Pull request merged**
